api todo
DiamondDmitriy/go-sprint-6 pull request #2
Opened 2024-10-23 20:04 UTC by DiamondDmitriy

2024-10-23 20:39 UTC, dirtymew requested changes
Привет Дмитрий

хорошая работа - API верно описан

но есть замечание - нужно доработать

2024-10-23 20:39 UTC, dirtymew commented on precode.go
> +		return
отлично что обработал ошибку - но можно так  `_, err = w.Write(resp)` раз ничего все равно не делается

2024-10-23 20:39 UTC, dirtymew commented on precode.go
> +	tasks[task.ID] = task
тут нужно проверить сначала что такой задачи еще нет

если есть вернуть ошибку

2024-10-24 08:11 UTC, DiamondDmitriy commented on precode.go
> +		return
Вы имеете ввиду удалить конструкцию if?

2024-10-24 12:35 UTC, dirtymew approved these changes
Дмитрий

все ок 

зачет

2024-10-24 21:31 UTC, dirtymew commented on precode.go
> +		return
@DiamondDmitriy сорри я опечатался

`_, _ = w.Write(resp)`

2024-11-05 16:07 UTC, merged